---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
      namespace: crud-app
    spec:
      initContainers:
        - name: init-db
          image: postgres:16
          command:
            [
              "sh",
              "-c",
              "until pg_isready -h db-svc -p 5432; do echo waiting for database; sleep 2; done;",
            ]
      containers:
        - name: backend
          image: final_assignment-backend
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: db_address
              value: db-svc
            - name: db_username
              value: postgres
            - name: db_name
              value: postgres
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-password
