---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: crud-app
  labels:
    app: backend-api
spec:
  type: ClusterIP
  selector:
    app: backend-api
  ports:
    - port: 8000

