---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-persistent-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: crud-app
    name: postgres-data-persistent-volume-claim
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/pgdata"

