---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-persistent-volume-claim
  namespace: crud-app
spec:
  volumeName: postgres-data-persistent-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
